# Generated by Django 4.1.6 on 2023-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillworkerapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Carpentry', 'Carpentry')], max_length=20, null=True),
        ),
    ]
